name: 'dbt_time'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'dbt_time'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
models:
  dbt_time:
    staging:
      +materialized: view
    marts:
      +materialized: table
    intermediate:
      +materialized: ephemeral

# Redshift specific configurations
vars:
  # Add any project-level variables here
  redshift_database: "dev"
  redshift_schema_staging: "staging"
  redshift_schema_prod: "public"
